name: actions workflow
on: [push]
jobs:
  run-githhhh:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        id: checkoutCode
        uses: actions/checkout@v3.0.2
      - name: list
        run: |
          pwd
          ls
      - name: simple action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Hellsmat
      - name: logg greeting time
        run: echo "${{ steps.greet.outputs.time }}"
