name: blablabla
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: "world"
      - run: |
          echo "time: ${{steps.hello.outputs.time}}"
